apiVersion: v1
kind: Service
metadata:
    name: "aksgj01"
    labels:
        app: "aksgj01"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "aksgj01"